# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-10 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='photo',
            field=models.ImageField(default='/photos/not-found.jpg', upload_to='photos'),
        ),
    ]
