# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-10 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_page_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='photo',
            field=models.ImageField(default='not-found.jpg', upload_to='album/photos'),
        ),
    ]
