# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-10 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0007_auto_20161110_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='photo',
            field=models.ImageField(default='img/not-found.jpg', upload_to='img/'),
        ),
    ]
